### ISSUE TITLE
问题qt的问题

### ISSUE THREAD

**Issue by IULOVE** [fjqisba/E-Debug#3]
你的qt5.6.3是自己编译的？ 不然你怎么可以mt编译？

**Comment by fjqisba** [comment]
不是，插件代码实质上还是调用的x64Dbg自身的qt模块，mt是使用静态运行库的意思吧，并没有去静态引用qt库

**Comment by IULOVE** [comment]
> 不是，插件代码实质上还是调用的x64Dbg自身的qt模块，mt是使用静态运行库的意思吧，并没有去静态引用qt库

嗯··我知道是用x64dbg的模块， 是的mt是静态运行库就是不带msvc那些dll， 你这个插件可以mt编译··我自己创建一个qt程序mt编译不了···下的是你放这里的连接的qt所以问下你。这qt是带那些运行库编译的

**Comment by IULOVE** [comment]
> 不是，插件代码实质上还是调用的x64Dbg自身的qt模块，mt是使用静态运行库的意思吧，并没有去静态引用qt库

你创建一个exe的qt工程可以mt编译吗

**Comment by fjqisba** [comment]
Qt的库应该是和C++的运行库是独立的，Qt的库分为Debug和Release两种模式，可在Build Config中进行设置，Debug就是使用qt5cored.dll，Release则是qt5core.dll。
C++运行库不管我设置MT还是MD，都不影响我使用Qt的dll
